// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5GiL3sGCGetwyih-89sE_axnIE_ftu5c',
    appId: '1:897097521161:web:c580e5fd4b8f0c7fa300d8',
    messagingSenderId: '897097521161',
    projectId: 'myvote-54ef6',
    authDomain: 'myvote-54ef6.firebaseapp.com',
    storageBucket: 'myvote-54ef6.firebasestorage.app',
    measurementId: 'G-0XGCJ0WEZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JfMnTkxTVHFHF-aLon6V3lZj024p9qw',
    appId: '1:897097521161:android:010c4622856448e9a300d8',
    messagingSenderId: '897097521161',
    projectId: 'myvote-54ef6',
    storageBucket: 'myvote-54ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrhXABqDPn01KnqYFE15AQCqzMlCpr_NQ',
    appId: '1:897097521161:ios:ce9ef9e5432ea354a300d8',
    messagingSenderId: '897097521161',
    projectId: 'myvote-54ef6',
    storageBucket: 'myvote-54ef6.firebasestorage.app',
    iosBundleId: 'com.example.myvote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrhXABqDPn01KnqYFE15AQCqzMlCpr_NQ',
    appId: '1:897097521161:ios:ce9ef9e5432ea354a300d8',
    messagingSenderId: '897097521161',
    projectId: 'myvote-54ef6',
    storageBucket: 'myvote-54ef6.firebasestorage.app',
    iosBundleId: 'com.example.myvote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5GiL3sGCGetwyih-89sE_axnIE_ftu5c',
    appId: '1:897097521161:web:780bc17944874d76a300d8',
    messagingSenderId: '897097521161',
    projectId: 'myvote-54ef6',
    authDomain: 'myvote-54ef6.firebaseapp.com',
    storageBucket: 'myvote-54ef6.firebasestorage.app',
    measurementId: 'G-7KV6T9C4VP',
  );
}
